<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecializationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specializations = [
            // Developers / Engineers
            [
                'name' => 'Frontend Developer',
                'slug' => 'frontend-developer',
                'description' => 'Specializes in client-side web development using HTML, CSS, JavaScript, and modern frameworks.',
                'category' => 'developers',
                'icon' => 'code',
                'skills' => ['HTML', 'CSS', 'JavaScript', 'React', 'Vue.js', 'Angular', 'TypeScript'],
                'tools' => ['VS Code', 'Chrome DevTools', 'Figma', 'Git', 'Webpack', 'Vite'],
                'sort_order' => 1,
            ],
            [
                'name' => 'Backend Developer',
                'slug' => 'backend-developer',
                'description' => 'Focuses on server-side development, APIs, databases, and system architecture.',
                'category' => 'developers',
                'icon' => 'server',
                'skills' => ['PHP', 'Python', 'Node.js', 'Java', 'C#', 'SQL', 'REST APIs'],
                'tools' => ['Laravel', 'Django', 'Express.js', 'PostgreSQL', 'MySQL', 'Redis'],
                'sort_order' => 2,
            ],
            [
                'name' => 'Full-Stack Developer',
                'slug' => 'fullstack-developer',
                'description' => 'Proficient in both frontend and backend development, capable of building complete applications.',
                'category' => 'developers',
                'icon' => 'layers',
                'skills' => ['Frontend & Backend', 'Database Design', 'API Development', 'System Architecture'],
                'tools' => ['Full Technology Stack', 'Cloud Platforms', 'DevOps Tools'],
                'sort_order' => 3,
            ],
            [
                'name' => 'Mobile App Developer',
                'slug' => 'mobile-developer',
                'description' => 'Develops mobile applications for iOS and Android platforms.',
                'category' => 'developers',
                'icon' => 'smartphone',
                'skills' => ['Swift', 'Kotlin', 'React Native', 'Flutter', 'iOS', 'Android'],
                'tools' => ['Xcode', 'Android Studio', 'React Native', 'Flutter', 'Firebase'],
                'sort_order' => 4,
            ],
            [
                'name' => 'Web Developer',
                'slug' => 'web-developer',
                'description' => 'General web development covering both frontend and backend aspects.',
                'category' => 'developers',
                'icon' => 'globe',
                'skills' => ['HTML', 'CSS', 'JavaScript', 'PHP', 'Python', 'Database Management'],
                'tools' => ['VS Code', 'Git', 'Docker', 'Cloud Platforms'],
                'sort_order' => 5,
            ],
            [
                'name' => 'Game Developer',
                'slug' => 'game-developer',
                'description' => 'Creates video games for various platforms including mobile, web, and desktop.',
                'category' => 'developers',
                'icon' => 'gamepad',
                'skills' => ['Unity', 'Unreal Engine', 'C#', 'C++', 'Game Design', '3D Graphics'],
                'tools' => ['Unity', 'Unreal Engine', 'Blender', 'Maya', 'Visual Studio'],
                'sort_order' => 6,
            ],
            [
                'name' => 'Embedded Systems Developer',
                'slug' => 'embedded-developer',
                'description' => 'Develops software for embedded systems and IoT devices.',
                'category' => 'developers',
                'icon' => 'cpu',
                'skills' => ['C', 'C++', 'Assembly', 'Microcontrollers', 'RTOS', 'Hardware Integration'],
                'tools' => ['Arduino', 'Raspberry Pi', 'STM32', 'Keil', 'Eclipse'],
                'sort_order' => 7,
            ],
            [
                'name' => 'DevOps Engineer',
                'slug' => 'devops-engineer',
                'description' => 'Manages deployment, infrastructure, and automation processes.',
                'category' => 'developers',
                'icon' => 'settings',
                'skills' => ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux', 'Automation'],
                'tools' => ['Docker', 'Jenkins', 'GitLab CI', 'Terraform', 'Ansible'],
                'sort_order' => 8,
            ],
            [
                'name' => 'Data Engineer',
                'slug' => 'data-engineer',
                'description' => 'Builds and maintains data infrastructure and pipelines.',
                'category' => 'developers',
                'icon' => 'database',
                'skills' => ['Python', 'SQL', 'Apache Spark', 'Hadoop', 'ETL', 'Data Modeling'],
                'tools' => ['Apache Airflow', 'Kafka', 'Elasticsearch', 'AWS', 'GCP'],
                'sort_order' => 9,
            ],
            [
                'name' => 'Cloud Engineer',
                'slug' => 'cloud-engineer',
                'description' => 'Specializes in cloud infrastructure, deployment, and management.',
                'category' => 'developers',
                'icon' => 'cloud',
                'skills' => ['AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Infrastructure as Code'],
                'tools' => ['Terraform', 'CloudFormation', 'Ansible', 'Jenkins'],
                'sort_order' => 10,
            ],
            [
                'name' => 'AI / Machine Learning Engineer',
                'slug' => 'ai-ml-engineer',
                'description' => 'Develops AI and machine learning solutions and models.',
                'category' => 'developers',
                'icon' => 'brain',
                'skills' => ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'Deep Learning', 'Data Science'],
                'tools' => ['Jupyter', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Pandas'],
                'sort_order' => 11,
            ],
            [
                'name' => 'Security Engineer',
                'slug' => 'security-engineer',
                'description' => 'Ensures system security through testing, analysis, and implementation of security measures.',
                'category' => 'developers',
                'icon' => 'shield',
                'skills' => ['Cybersecurity', 'Penetration Testing', 'Security Analysis', 'Risk Assessment'],
                'tools' => ['Burp Suite', 'Nmap', 'Wireshark', 'Metasploit', 'OWASP'],
                'sort_order' => 12,
            ],
            [
                'name' => 'QA / Test Automation Engineer',
                'slug' => 'qa-automation-engineer',
                'description' => 'Develops and maintains automated testing solutions and quality assurance processes.',
                'category' => 'developers',
                'icon' => 'check-circle',
                'skills' => ['Test Automation', 'Selenium', 'Cypress', 'Jest', 'Quality Assurance'],
                'tools' => ['Selenium', 'Cypress', 'Jest', 'Postman', 'TestRail'],
                'sort_order' => 13,
            ],

            // Designers / Creatives
            [
                'name' => 'UI Designer',
                'slug' => 'ui-designer',
                'description' => 'Creates user interface designs focusing on visual elements and layout.',
                'category' => 'designers',
                'icon' => 'palette',
                'skills' => ['UI Design', 'Visual Design', 'Typography', 'Color Theory', 'Layout Design'],
                'tools' => ['Figma', 'Sketch', 'Adobe XD', 'Photoshop', 'Illustrator'],
                'sort_order' => 14,
            ],
            [
                'name' => 'UX Designer',
                'slug' => 'ux-designer',
                'description' => 'Focuses on user experience, research, and interaction design.',
                'category' => 'designers',
                'icon' => 'users',
                'skills' => ['User Research', 'Wireframing', 'Prototyping', 'Usability Testing', 'Information Architecture'],
                'tools' => ['Figma', 'Sketch', 'InVision', 'Maze', 'Hotjar'],
                'sort_order' => 15,
            ],
            [
                'name' => 'Web Designer',
                'slug' => 'web-designer',
                'description' => 'Designs websites with focus on visual appeal and user experience.',
                'category' => 'designers',
                'icon' => 'monitor',
                'skills' => ['Web Design', 'Responsive Design', 'HTML/CSS', 'Visual Design', 'User Experience'],
                'tools' => ['Figma', 'Adobe Creative Suite', 'Webflow', 'WordPress'],
                'sort_order' => 16,
            ],
            [
                'name' => 'Graphic Designer',
                'slug' => 'graphic-designer',
                'description' => 'Creates visual content including logos, branding, and marketing materials.',
                'category' => 'designers',
                'icon' => 'image',
                'skills' => ['Graphic Design', 'Branding', 'Typography', 'Print Design', 'Digital Design'],
                'tools' => ['Photoshop', 'Illustrator', 'InDesign', 'Canva', 'Figma'],
                'sort_order' => 17,
            ],
            [
                'name' => 'Motion Designer',
                'slug' => 'motion-designer',
                'description' => 'Creates animated content and motion graphics for digital media.',
                'category' => 'designers',
                'icon' => 'play',
                'skills' => ['Motion Graphics', 'Animation', 'Video Editing', '2D/3D Animation'],
                'tools' => ['After Effects', 'Cinema 4D', 'Blender', 'Premiere Pro'],
                'sort_order' => 18,
            ],
            [
                'name' => '3D Designer / Artist',
                'slug' => '3d-designer',
                'description' => 'Creates 3D models, animations, and visualizations.',
                'category' => 'designers',
                'icon' => 'box',
                'skills' => ['3D Modeling', 'Texturing', 'Rendering', 'Animation', '3D Visualization'],
                'tools' => ['Blender', 'Maya', '3ds Max', 'Cinema 4D', 'ZBrush'],
                'sort_order' => 19,
            ],
            [
                'name' => 'Product Designer',
                'slug' => 'product-designer',
                'description' => 'Designs digital products with focus on user needs and business goals.',
                'category' => 'designers',
                'icon' => 'package',
                'skills' => ['Product Design', 'User Research', 'Prototyping', 'Design Systems', 'Strategy'],
                'tools' => ['Figma', 'Sketch', 'Principle', 'Miro', 'Notion'],
                'sort_order' => 20,
            ],
            [
                'name' => 'Interaction Designer',
                'slug' => 'interaction-designer',
                'description' => 'Designs how users interact with digital products and interfaces.',
                'category' => 'designers',
                'icon' => 'mouse-pointer',
                'skills' => ['Interaction Design', 'Prototyping', 'User Flows', 'Micro-interactions'],
                'tools' => ['Figma', 'Principle', 'Framer', 'InVision', 'Axure'],
                'sort_order' => 21,
            ],

            // Management / Coordination
            [
                'name' => 'Project Manager',
                'slug' => 'project-manager',
                'description' => 'Manages project timelines, resources, and team coordination.',
                'category' => 'management',
                'icon' => 'clipboard',
                'skills' => ['Project Management', 'Agile', 'Scrum', 'Team Leadership', 'Risk Management'],
                'tools' => ['Jira', 'Asana', 'Trello', 'Monday.com', 'Slack'],
                'sort_order' => 22,
            ],
            [
                'name' => 'Product Manager',
                'slug' => 'product-manager',
                'description' => 'Defines product strategy, roadmap, and coordinates development.',
                'category' => 'management',
                'icon' => 'target',
                'skills' => ['Product Strategy', 'Market Research', 'Roadmapping', 'Stakeholder Management'],
                'tools' => ['ProductBoard', 'Aha!', 'Jira', 'Confluence', 'Analytics Tools'],
                'sort_order' => 23,
            ],
            [
                'name' => 'Scrum Master / Agile Coach',
                'slug' => 'scrum-master',
                'description' => 'Facilitates agile processes and team development.',
                'category' => 'management',
                'icon' => 'users',
                'skills' => ['Scrum', 'Agile', 'Team Facilitation', 'Process Improvement'],
                'tools' => ['Jira', 'Confluence', 'Miro', 'Retrospectives', 'Planning Tools'],
                'sort_order' => 24,
            ],
            [
                'name' => 'Technical Lead / Team Lead',
                'slug' => 'technical-lead',
                'description' => 'Provides technical leadership and mentorship to development teams.',
                'category' => 'management',
                'icon' => 'user-check',
                'skills' => ['Technical Leadership', 'Architecture', 'Code Review', 'Mentoring'],
                'tools' => ['Git', 'Code Review Tools', 'Architecture Tools', 'Documentation'],
                'sort_order' => 25,
            ],
            [
                'name' => 'CTO / Head of Technology',
                'slug' => 'cto',
                'description' => 'Oversees technology strategy and technical direction of the organization.',
                'category' => 'management',
                'icon' => 'crown',
                'skills' => ['Technology Strategy', 'Leadership', 'Architecture', 'Business Strategy'],
                'tools' => ['Strategic Planning', 'Architecture Tools', 'Business Intelligence'],
                'sort_order' => 26,
            ],

            // Specialized IT Roles
            [
                'name' => 'Database Administrator (DBA)',
                'slug' => 'database-administrator',
                'description' => 'Manages and maintains database systems and performance.',
                'category' => 'specialized_it',
                'icon' => 'database',
                'skills' => ['Database Management', 'SQL', 'Performance Tuning', 'Backup & Recovery'],
                'tools' => ['PostgreSQL', 'MySQL', 'Oracle', 'MongoDB', 'Redis'],
                'sort_order' => 27,
            ],
            [
                'name' => 'System Administrator',
                'slug' => 'system-administrator',
                'description' => 'Manages server infrastructure and system operations.',
                'category' => 'specialized_it',
                'icon' => 'server',
                'skills' => ['Linux', 'Windows Server', 'Networking', 'System Monitoring'],
                'tools' => ['Linux', 'Windows Server', 'Nagios', 'Zabbix', 'Ansible'],
                'sort_order' => 28,
            ],
            [
                'name' => 'Network Engineer',
                'slug' => 'network-engineer',
                'description' => 'Designs and maintains network infrastructure and security.',
                'category' => 'specialized_it',
                'icon' => 'network',
                'skills' => ['Network Design', 'Routing', 'Switching', 'Security', 'Troubleshooting'],
                'tools' => ['Cisco', 'Juniper', 'Wireshark', 'Ping', 'Traceroute'],
                'sort_order' => 29,
            ],
            [
                'name' => 'Solutions Architect',
                'slug' => 'solutions-architect',
                'description' => 'Designs technical solutions and system architecture.',
                'category' => 'specialized_it',
                'icon' => 'layers',
                'skills' => ['System Architecture', 'Technology Selection', 'Integration', 'Scalability'],
                'tools' => ['Architecture Tools', 'Cloud Platforms', 'Integration Tools'],
                'sort_order' => 30,
            ],
            [
                'name' => 'Business Analyst',
                'slug' => 'business-analyst',
                'description' => 'Analyzes business requirements and translates them into technical solutions.',
                'category' => 'specialized_it',
                'icon' => 'bar-chart',
                'skills' => ['Requirements Analysis', 'Process Mapping', 'Stakeholder Management', 'Documentation'],
                'tools' => ['Visio', 'Lucidchart', 'Jira', 'Confluence', 'Excel'],
                'sort_order' => 31,
            ],
            [
                'name' => 'Data Scientist',
                'slug' => 'data-scientist',
                'description' => 'Analyzes data to extract insights and build predictive models.',
                'category' => 'specialized_it',
                'icon' => 'trending-up',
                'skills' => ['Python', 'R', 'Machine Learning', 'Statistics', 'Data Analysis'],
                'tools' => ['Jupyter', 'Pandas', 'Scikit-learn', 'TensorFlow', 'Tableau'],
                'sort_order' => 32,
            ],
            [
                'name' => 'SEO / Digital Marketing Specialist',
                'slug' => 'seo-marketing-specialist',
                'description' => 'Optimizes digital presence and implements marketing strategies.',
                'category' => 'specialized_it',
                'icon' => 'search',
                'skills' => ['SEO', 'Digital Marketing', 'Analytics', 'Content Strategy', 'Social Media'],
                'tools' => ['Google Analytics', 'SEMrush', 'Ahrefs', 'Hootsuite', 'Mailchimp'],
                'sort_order' => 33,
            ],

            // Support / Cross-Functional
            [
                'name' => 'IT Support Specialist',
                'slug' => 'it-support-specialist',
                'description' => 'Provides technical support and troubleshooting for IT systems.',
                'category' => 'support',
                'icon' => 'help-circle',
                'skills' => ['Technical Support', 'Troubleshooting', 'Customer Service', 'System Maintenance'],
                'tools' => ['Help Desk Software', 'Remote Desktop', 'System Monitoring', 'Documentation'],
                'sort_order' => 34,
            ],
            [
                'name' => 'Customer Success Engineer',
                'slug' => 'customer-success-engineer',
                'description' => 'Ensures customer satisfaction and technical success with products.',
                'category' => 'support',
                'icon' => 'heart',
                'skills' => ['Customer Success', 'Technical Support', 'Account Management', 'Problem Solving'],
                'tools' => ['CRM', 'Support Tools', 'Analytics', 'Communication Tools'],
                'sort_order' => 35,
            ],
            [
                'name' => 'Technical Writer',
                'slug' => 'technical-writer',
                'description' => 'Creates technical documentation and user guides.',
                'category' => 'support',
                'icon' => 'file-text',
                'skills' => ['Technical Writing', 'Documentation', 'API Documentation', 'User Guides'],
                'tools' => ['Confluence', 'GitBook', 'Sphinx', 'Markdown', 'Git'],
                'sort_order' => 36,
            ],
            [
                'name' => 'QA Tester (Manual)',
                'slug' => 'qa-tester-manual',
                'description' => 'Performs manual testing and quality assurance of software products.',
                'category' => 'support',
                'icon' => 'check-square',
                'skills' => ['Manual Testing', 'Bug Reporting', 'Test Cases', 'Quality Assurance'],
                'tools' => ['TestRail', 'Jira', 'Bug Tracking Tools', 'Testing Tools'],
                'sort_order' => 37,
            ],
        ];

        foreach ($specializations as $specialization) {
            DB::table('specializations')->updateOrInsert(
                ['slug' => $specialization['slug']],
                array_merge($specialization, [
                    'skills' => json_encode($specialization['skills']),
                    'tools' => json_encode($specialization['tools']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}