name: CI

on:
  push:
    branches: [ imhotion_v2, main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, xml, bcmath, pcntl, json, curl
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Install Node dependencies
        run: |
          npm ci

      - name: Prepare app
        env:
          APP_ENV: testing
        run: |
          cp .env.example .env || true
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          php artisan key:generate --ansi

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --fail-on-empty

      - name: Build assets
        run: npm run build --if-present
